"""Stage 5 — DPO (Direct Preference Optimization) trainer.

DPO fine-tunes a model so that it prefers correct vulnerability classifications
and patches over incorrect ones, using a preference dataset of
(chosen, rejected) response pairs.

In this harness, the "chosen" response is the ground-truth
``InstructionExample`` target (correct CWE + fix), and the "rejected"
response is a naive baseline generated from the base (un-tuned) model's
zero-shot output (see Stage 4's ``MockBackend`` / ``QwenBackend`` for the
baseline generation path).

Heavy ML imports (``transformers``, ``trl``, ``torch``) are imported lazily
inside ``_run_dpo``, mirroring the SFT trainer's pattern. The ``run_dpo``
function supports ``dry_run=True`` so it works in CI without a GPU.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from typing import Any

from app.schemas.dataset import InstructionExample
from app.schemas.training import TrainingResult
from app.training.callbacks import (
    ProgressCallback,
    ResourceTracker,
    WandbCallback,
    notify_callbacks_end,
    notify_callbacks_init,
    save_checkpoint,
)
from app.training.config import DPOConfig
from app.training.data import JsonlDataLoader, load_examples

logger = logging.getLogger(__name__)


class DPOUnavailableError(RuntimeError):
    """Raised when DPO training is attempted but the ML stack is absent."""


@dataclass
class DPOStepEstimate:
    """Estimated DPO training steps."""

    n_pairs: int
    steps_per_epoch: int
    total_steps: int
    estimated_vram_gb: float
    can_fit_in_8gb: bool


def estimate_dpo_steps(
    config: DPOConfig,
    n_pairs: int,
) -> DPOStepEstimate:
    """Compute the number of DPO optimiser steps and a VRAM heuristic.

    Pure arithmetic — no GPU or torch required.
    """
    steps_per_epoch = max(1, n_pairs // config.per_device_train_batch_size)
    optim_steps_per_epoch = max(1, steps_per_epoch // config.gradient_accumulation_steps)
    total_steps = optim_steps_per_epoch * config.num_train_epochs

    # DPO reference model + policy model together: ~10-12 GB for 7B in 16-bit.
    est_vram = 12.0
    return DPOStepEstimate(
        n_pairs=n_pairs,
        steps_per_epoch=optim_steps_per_epoch,
        total_steps=total_steps,
        estimated_vram_gb=est_vram,
        can_fit_in_8gb=est_vram <= 8.0,
    )


def build_preference_pairs(
    train_examples: list[InstructionExample],
    rejected_examples: list[InstructionExample] | None = None,
) -> list[dict]:
    """Build (chosen, rejected) preference pairs for DPO.

    The "chosen" response is the ground-truth from ``InstructionExample``.
    The "rejected" response is either:
    - A matching example from ``rejected_examples`` (if provided, same index), or
    - A synthetic low-quality response generated by ``_make_rejected_response``.

    Each pair dict has ``prompt``, ``chosen``, ``rejected`` keys (the format
    expected by ``trl``'s ``DPOTrainer``).
    """
    pairs: list[dict] = []
    for i, ex in enumerate(train_examples):
        chosen = _format_response(ex)
        if rejected_examples and i < len(rejected_examples):
            rejected = _format_response(rejected_examples[i])
        else:
            rejected = _make_rejected_response(ex)
        pairs.append(
            {
                "prompt": ex.prompt,
                "chosen": chosen,
                "rejected": rejected,
            }
        )
    return pairs


def _format_response(ex: InstructionExample) -> str:
    """Format an ``InstructionExample`` as a JSON response string (the model output)."""
    obj = {
        "cwe_id": ex.target_cwe,
        "severity": ex.target_severity,
        "explanation": ex.target_explanation,
        "patch_diff": ex.target_patch_diff,
    }
    return json.dumps(obj, ensure_ascii=False)


def _make_rejected_response(ex: InstructionExample) -> str:
    """Generate a low-quality / incorrect response as the DPO "rejected" example.

    This simulates what the base (un-fine-tuned) model might produce: wrong CWE,
    shallow explanation, empty patch. The exact behaviour doesn't matter much —
    what matters is that it's systematically worse than the chosen response.
    """
    # Pick a wrong CWE from the same scope (deterministic: shift by 2).
    cwe_scope = ["CWE-89", "CWE-79", "CWE-22", "CWE-78", "CWE-190", "CWE-502"]
    try:
        idx = cwe_scope.index(ex.target_cwe)
        wrong_cwe = cwe_scope[(idx + 3) % len(cwe_scope)]
    except ValueError:
        wrong_cwe = "CWE-89"

    obj = {
        "cwe_id": wrong_cwe,
        "severity": "low",
        "explanation": "I'm not sure what vulnerability this is.",
        "patch_diff": "",
    }
    return json.dumps(obj, ensure_ascii=False)


def _apply_fsdp_compat_shim() -> None:
    """Patch ``FSDPModule`` onto ``torch.distributed.fsdp`` if missing.

    trl >= 1.0 imports ``FSDPModule`` from ``torch.distributed.fsdp``, which was
    removed in torch >= 2.3.  Best-effort only: skips gracefully whenever torch
    is mocked, the submodule is unavailable, or version skew makes the shim
    inapplicable.  Must never abort training.
    """
    try:
        import torch.distributed.fsdp as _fsdp_mod

        if not hasattr(_fsdp_mod, "FSDPModule"):
            _fsdp_mod.FSDPModule = _fsdp_mod.FullyShardedDataParallel  # type: ignore[attr-defined]
    except Exception as exc:  # noqa: BLE001
        logger.debug("Skipping FSDPModule compat shim: %s", exc)


def _dpo_load_model(config: DPOConfig):
    """Load the base model + PEFT adapter for DPO.

    Returns the model (with KV cache disabled and gradient config set).
    """
    import torch
    from transformers import (
        AutoModelForCausalLM,
        BitsAndBytesConfig,
    )

    _apply_fsdp_compat_shim()

    # Always load from the base model first, then layer the LoRA adapter on top.
    # config.sft_checkpoint is a PEFT adapter dir (contains adapter_config.json
    # but not full model weights) — passing it to from_pretrained directly would fail.
    #
    # Use 4-bit QLoRA loading (same pattern as trainer_sft.py) so the 1.5B base
    # model fits in ~1 GB instead of ~3 GB in bfloat16, leaving headroom for
    # activations, gradients, optimizer state, and the DPO reference model.
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )
    # Explicitly cap GPU memory to force layers to offload to CPU as needed.
    # 8GB VRAM constraint: 7GB cap leaves headroom for CUDA runtime overhead.
    # Only set for device 0 — multi-device maps cause CUDA init errors on single-GPU.
    max_memory = {0: "7GB"}
    model = AutoModelForCausalLM.from_pretrained(  # nosec B615
        config.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        max_memory=max_memory,
        trust_remote_code=True,
    )

    if config.sft_checkpoint and os.path.exists(config.sft_checkpoint):
        from peft import PeftModel, prepare_model_for_kbit_training

        model = prepare_model_for_kbit_training(model)
        model = PeftModel.from_pretrained(model, config.sft_checkpoint, is_trainable=True)
        logger.info(
            "Loaded SFT LoRA checkpoint from %s (4-bit QLoRA DPO mode)",
            config.sft_checkpoint,
        )
    else:
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

        model = prepare_model_for_kbit_training(model)
        lora_config = LoraConfig(
            r=64,
            lora_alpha=16,
            lora_dropout=0.05,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
            bias="none",
            task_type="CAUSAL_LM",
        )
        model = get_peft_model(model, lora_config)
        logger.info("Loaded base model in 4-bit with fresh LoRA adapters (QLoRA DPO mode)")

    # DPO training needs the KV cache disabled. For PEFT models, only adapter
    # params require grad — PEFT sets this automatically, so we must NOT call
    # model.requires_grad_(True) which would try to train all base params.
    model.config.use_cache = False
    if hasattr(model, "base_model"):
        # PEFT model: freeze base, unfreeze adapter
        model.base_model.requires_grad_(False)
        for name, param in model.named_parameters():
            if "lora_" in name or param.requires_grad:
                param.requires_grad = True
    return model


def _run_dpo(
    config: DPOConfig,
    train_pairs: list[dict],
    val_pairs: list[dict] | None,
    callbacks: list,
    run_id: str,
) -> TrainingResult:
    """Internal: perform the actual DPO training loop.

    Lazy-imports torch/transformers/trl inside this function.
    """
    from datasets import Dataset
    from transformers import AutoTokenizer
    from trl import DPOConfig as TrlDPOConfig
    from trl import DPOTrainer

    tracker = ResourceTracker()
    tracker.start()

    # --- Notify callbacks ---
    hp = {
        "base_model": config.base_model,
        "method": "dpo",
        "beta": config.beta,
        "loss_type": config.loss_type,
        "learning_rate": config.learning_rate,
        "num_train_epochs": config.num_train_epochs,
        "sft_checkpoint": config.sft_checkpoint,
    }
    notify_callbacks_init(callbacks, hp)

    # --- Load model ---
    model = _dpo_load_model(config)

    tokenizer = AutoTokenizer.from_pretrained(  # nosec B615
        config.base_model, trust_remote_code=True
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # --- TRL DPO config ---
    rl_config = TrlDPOConfig(
        output_dir=config.output_dir,
        per_device_train_batch_size=config.per_device_train_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        learning_rate=config.learning_rate,
        num_train_epochs=config.num_train_epochs,
        warmup_ratio=config.warmup_ratio,
        weight_decay=config.weight_decay,
        max_grad_norm=config.max_grad_norm,
        beta=config.beta,
        loss_type=config.loss_type,
        report_to="none",  # we handle W&B via our own callback
        run_name=config.run_name or run_id,
        # bf16 / fp16 autocast must be False: the model is always loaded in
        # 4-bit QLoRA (bnb_4bit_compute_dtype=torch.bfloat16) which handles
        # precision internally.  Enabling bf16=True here triggers the
        # torch.cpu.amp.autocast FutureWarning (and an F16→F32 CUDA kernel
        # assertion on some driver/torch combos) inside gradient checkpointing
        # when layers are offloaded to CPU via max_memory={0: "7GB"}.
        # This mirrors trainer_sft.py, which also disables both flags in
        # QLoRA mode (use_4bit=True && use_cuda=True → fp16=bf16=False).
        # use_reentrant=False further avoids the legacy reentrant autograd
        # path that caused the same warnings in Stage 9 GPU serving.
        bf16=False,
        fp16=False,
        # Gradient checkpointing reduces activation memory by recomputing
        # during the backward pass — essential for DPO on 8GB VRAM.
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        # Bound sequence length to keep attention matrix + logits memory predictable.
        # DPO compares two responses per sample, so we keep both short.
        # 256 is sufficient for vulnerability descriptions and patch diffs.
        # trl 1.9.2's DPOConfig only has max_length (no separate max_prompt_length).
        max_length=256,
    )

    # Convert lists to HF Datasets — DPOTrainer expects Dataset objects (with .map())
    train_ds = Dataset.from_list(train_pairs)
    val_ds = Dataset.from_list(val_pairs) if val_pairs else None

    trainer = DPOTrainer(
        model=model,
        args=rl_config,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        processing_class=tokenizer,
    )

    trainer.add_callback(_LossCallback)
    train_result = trainer.train()

    # Retrieve the callback instance the Trainer created from the class.
    # When the Trainer is a MagicMock (unit tests) there is no
    # callback_handler, so fall back to an empty list.
    loss_callback = next(
        (
            cb
            for cb in getattr(
                getattr(trainer, "callback_handler", None),
                "callbacks",
                [],
            )
            if isinstance(cb, _LossCallback)
        ),
        _LossCallback(),
    )
    loss_history = loss_callback.losses
    final_train_loss = float(
        train_result.metrics.get("train_loss", loss_history[-1] if loss_history else 0.0)
    )
    final_val_loss = _eval_if_present(trainer, val_pairs)
    tracker.record_peak_memory()

    checkpoint_uri = save_checkpoint(
        callbacks,
        config.output_dir,
        model,
        tokenizer,
        run_id,
        config.num_train_epochs,
    )

    result = TrainingResult(
        run_id=run_id,
        method="dpo",
        base_model=config.base_model,
        hyperparams={
            "beta": config.beta,
            "loss_type": config.loss_type,
            "learning_rate": config.learning_rate,
            "num_train_epochs": config.num_train_epochs,
        },
        train_set_size=len(train_pairs),
        train_time_minutes=tracker.elapsed_minutes,
        peak_vram_gb=tracker.peak_vram_gb,
        final_train_loss=final_train_loss,
        final_val_loss=final_val_loss,
        checkpoint_uri=checkpoint_uri,
        status="completed",
        run_name=config.run_name,
        train_loss_history=loss_history,
    )
    notify_callbacks_end(callbacks, result)
    return result


class _LossCallback:
    """TrainerCallback that captures per-step loss values.

    Uses ``__slots__``-free design so the callback is picklable and
    trivially inspectable in tests.
    """

    def __init__(self) -> None:
        self.losses: list[float] = []

    def on_log(
        self,
        args: Any,
        state: Any,
        control: Any,
        logs: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        if logs and "loss" in logs:
            self.losses.append(logs["loss"])


def _eval_if_present(trainer, val_pairs) -> float | None:
    """Evaluate and return ``final_val_loss`` when ``val_pairs`` is set.

    Returns ``None`` when there is no validation data.
    """
    if not val_pairs:
        return None
    eval_metrics = trainer.evaluate()
    return float(eval_metrics.get("eval_loss", 0.0))


def _check_can_train(config: DPOConfig) -> None:
    """Verify the ML stack is importable and a GPU is available."""
    try:
        import torch  # noqa: F401
        import transformers  # noqa: F401
        import trl  # noqa: F401
    except ImportError as exc:
        raise DPOUnavailableError(
            "torch/transformers/trl not installed. Run `pip install -e '.[ml]'` "
            "to train, or use `--dry-run` for a step estimate."
        ) from exc

    if not torch.cuda.is_available():
        raise DPOUnavailableError(
            "No CUDA GPU detected. DPO training requires a GPU with >=10 GB VRAM. "
            "Use `--dry-run` for an estimate."
        )


def _default_callbacks(run_id: str) -> list:
    return [
        WandbCallback(run_name=run_id, mock=True),
        ProgressCallback(verbose=False),
    ]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def _validate_train_path(train_jsonl: str) -> None:
    """Raise FileNotFoundError if *train_jsonl* is empty or doesn't exist."""
    if not (train_jsonl and os.path.exists(train_jsonl)):
        raise FileNotFoundError(
            f"train_jsonl path is empty or does not exist: {train_jsonl!r}. "
            "Provide --train-jsonl or set DPOConfig.train_jsonl."
        )


def _load_dpo_data(
    train_jsonl: str,
    val_path: str,
    rejected_path: str,
    loader: Any | None,
) -> tuple:
    """Load train / val / rejected examples and build preference pairs."""
    ld = loader or JsonlDataLoader()
    train_examples = load_examples(train_jsonl, loader=ld)
    val_examples = load_examples(val_path, loader=ld) if val_path else []
    rejected_examples = load_examples(rejected_path, loader=ld) if rejected_path else None

    train_pairs = build_preference_pairs(train_examples, rejected_examples)
    val_pairs = build_preference_pairs(val_examples) if val_examples else None
    return train_pairs, val_pairs


def _dpo_dry_run(
    config: DPOConfig,
    callbacks: list,
    run_id: str,
    train_pairs: list,
) -> TrainingResult:
    """Execute the dry-run path and return an estimated ``TrainingResult``."""
    estimate = estimate_dpo_steps(config, len(train_pairs))
    logger.info(
        "DPO dry-run: %d pairs, %d steps, est. VRAM %.1f GB",
        estimate.n_pairs,
        estimate.total_steps,
        estimate.estimated_vram_gb,
    )
    for cb in callbacks:
        cb.on_init(
            {
                "method": "dpo",
                "base_model": config.base_model,
                "dry_run": True,
                "n_pairs": estimate.n_pairs,
                "estimated_steps": estimate.total_steps,
                "estimated_vram_gb": estimate.estimated_vram_gb,
            }
        )
    for cb in callbacks:
        cb.on_train_end(
            final_train_loss=0.0,
            final_val_loss=None,
            peak_vram_gb=estimate.estimated_vram_gb,
            train_time_minutes=0.0,
        )
    return TrainingResult(
        run_id=run_id,
        method="dpo",
        base_model=config.base_model,
        hyperparams={
            "beta": config.beta,
            "loss_type": config.loss_type,
            "learning_rate": config.learning_rate,
            "num_train_epochs": config.num_train_epochs,
        },
        train_set_size=len(train_pairs),
        train_time_minutes=0.0,
        peak_vram_gb=estimate.estimated_vram_gb,
        final_train_loss=0.0,
        final_val_loss=None,
        checkpoint_uri="",
        status="dry_run",
        run_name=config.run_name,
    )


def run_dpo(
    config: DPOConfig,
    train_path: str = "",
    val_path: str = "",
    *,
    callbacks: list | None = None,
    run_id: str | None = None,
    dry_run: bool = False,
    loader: Any | None = None,
    rejected_path: str = "",
) -> TrainingResult:
    """Run a single DPO training experiment.

    Parameters
    ----------
    config:
        ``DPOConfig`` with hyperparameters.
    train_path:
        Path to Stage 3 ``train.jsonl`` (the "chosen" responses).
    val_path:
        Optional path to a validation JSONL.
    callbacks:
        Injectable callbacks (default: mock-W&B + progress).
    run_id:
        Override the generated run ID.
    dry_run:
        If True, skip actual training and return an estimated ``TrainingResult``.
    loader:
        Injectable data loader for testing.
    rejected_path:
        Optional path to a JSONL of "rejected" responses (same format as train).
        If empty, synthetic rejected responses are generated from the train set.
    """
    train_jsonl = train_path or config.train_jsonl
    _validate_train_path(train_jsonl)

    if run_id is None:
        from app.training.experiment import generate_run_id

        run_id = generate_run_id("dpo", config.run_name)

    callbacks = callbacks if callbacks is not None else _default_callbacks(run_id)

    train_pairs, val_pairs = _load_dpo_data(train_jsonl, val_path, rejected_path, loader)

    if dry_run:
        return _dpo_dry_run(config, callbacks, run_id, train_pairs)

    # --- Real training ---
    _check_can_train(config)

    for cb in callbacks:
        cb.on_init(
            {
                "method": "dpo",
                "base_model": config.base_model,
                "sft_checkpoint": config.sft_checkpoint,
            }
        )

    try:
        return _run_dpo(config, train_pairs, val_pairs, callbacks, run_id)
    except Exception as exc:  # noqa: BLE001
        for cb in callbacks:
            cb.on_error(str(exc))
        raise
